Repository Weit-2nd/roady-foody-server, pull requests merged in 2024-06, with the labels that each got.

#6 ROFO-20 간단한 유저 도메인 및 시큐리티 설정, 필터 작성
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/config/JpaAuditingConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/controller/ExceptionHandler.kt
  src/main/kotlin/kr/weit/roadyfoody/controller/TestController.kt
  src/main/kotlin/kr/weit/roadyfoody/domain/BaseTimeEntity.kt
  src/main/kotlin/kr/weit/roadyfoody/domain/user/User.kt
  src/main/kotlin/kr/weit/roadyfoody/domain/user/UserRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/security/filter/MockPassFilter.kt
  src/main/kotlin/kr/weit/roadyfoody/security/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/kr/weit/roadyfoody/support/exception/CustomExceptions.kt
  src/main/kotlin/kr/weit/roadyfoody/support/jsonmapper/ObjectMapperProvider.kt
  src/main/kotlin/kr/weit/roadyfoody/support/regex/ValidationRegex.kt
  src/main/kotlin/kr/weit/roadyfoody/swagger/v1/TestControllerSpec.kt
  src/main/resources/application-flyway.yml
  src/main/resources/db/migration/V1__create_users.sql
  src/test/kotlin/kr/weit/roadyfoody/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/domain/user/UserRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/domain/user/UserTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/RepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/KotestConfig.kt
  src/test/kotlin/kr/weit/roadyfoody/support/fixture/UserFixture.kt
  src/test/resources/testcontainers/init.sql
Labels: documentation, enhancement

#7 ROFO-22 백엔드 이슈 트랜지션 걷어내기
  .github/workflows/issueTransition.yml
Labels: setting

#10 ROFO-30 RestClient 설정
  src/main/kotlin/kr/weit/roadyfoody/common/exception/BaseException.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/CustomExceptions.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/RetriesExceededException.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
  src/main/kotlin/kr/weit/roadyfoody/test/application/client/TestClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/test/application/client/TodoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/test/presentation/api/TestController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/exception/UserNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/user/repository/UserRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
  src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/repository/UserRepositoryTest.kt
Labels: enhancement

#11 ROFO-36 Swagger Authorize UI 적용
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/test/presentation/spec/TestControllerSpec.kt
Labels: enhancement

#12 ROFO-35 약관 조회 API 개발
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/term/domain/Term.kt
  src/main/kotlin/kr/weit/roadyfoody/term/exception/TermNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/term/presentation/api/TermController.kt
  src/main/kotlin/kr/weit/roadyfoody/term/presentation/spec/TermControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/term/repository/TermRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/term/service/TermCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/term/service/TermQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/term/service/dto/DetailedTermResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/term/service/dto/SummaryTermsResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/exception/UserNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/domain/UserAgreedTerm.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/exception/RequiredTermNotAgreedException.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/repository/UserAgreedTermRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/service/UserAgreedTermCommandService.kt
  src/main/resources/db/migration/V2__create_terms_and_user_agreed_terms.sql
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/utils/MockMvcHelper.kt
  src/test/kotlin/kr/weit/roadyfoody/term/controller/TermControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/fixture/TermDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/term/fixture/TermFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/term/repository/TermRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/service/TermCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/service/TermQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/repository/UserRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/useragreedterm/fixture/UserAgreedTermFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/useragreedterm/service/UserAgreedTermCommandServiceTest.kt
Labels: enhancement

#14 ROFO-37 관광공사 검색 API 연동
  src/main/kotlin/kr/weit/roadyfoody/common/annotation/ClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/RestClientException.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/EnablePropertiesConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/ThreadConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/test/application/client/TestClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/test/application/client/TodoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/test/presentation/api/TestController.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/config/TourismProperties.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/dto/ItemsDeserializer.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/dto/SearchResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/dto/TourismResponseWrapper.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/api/TourismController.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/client/TourismClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/spec/TourismControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
  src/main/resources/application-api.yml
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptorTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/IntegrateTestConfig.kt
  src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/tourism/fixture/TourismFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/tourism/presentation/api/TourismControllerTest.kt
  src/test/resources/payload/festival-search-response-size-0.json
  src/test/resources/payload/festival-search-response-size-2.json
  src/test/resources/payload/festival-search-response.json
  src/test/resources/payload/tour-search-response-size-0.json
  src/test/resources/payload/tour-search-response-size-2.json
  src/test/resources/payload/tour-search-response.json
Labels: enhancement

#15 ROFO-47 음식점 & 리뷰 엔티티 작성
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/DayOfWeek.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHoursId.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsPhoto.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/FoodSpotsNameRegex.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReviewPhoto.kt
  src/main/resources/db/migration/V3__create_food_spots_and_review.sql
Labels: enhancement

#17 ROFO-52 관광 검색 API 명확하게 문서화
  src/main/kotlin/kr/weit/roadyfoody/tourism/dto/SearchResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/spec/TourismControllerSpec.kt
Labels: documentation

#18 ROFO-42 회원가입 API 작성
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/dto/DuplicatedNicknameResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/dto/KakaoUserResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/InvalidTokenException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserAlreadyExistsException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/client/KakaoClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/filter/MockPassFilter.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/kr/weit/roadyfoody/common/controller/ExceptionHandler.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/converter/MultipartJackson2HttpMessageConverter.kt
  src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/MimeUtils.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/ObjectMapperProvider.kt
  src/main/kotlin/kr/weit/roadyfoody/global/validator/MaxFileSizeValidator.kt
  src/main/kotlin/kr/weit/roadyfoody/global/validator/WebPValidator.kt
  src/main/kotlin/kr/weit/roadyfoody/term/exception/TermNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/SocialLoginType.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/User.kt
  src/main/kotlin/kr/weit/roadyfoody/user/repository/UserRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/exception/RequiredTermNotAgreedException.kt
  src/main/resources/db/migration/V4__alter_users_add_profile.sql
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/service/ImageServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/utils/MimeUtilsTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerIntegrateTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/utils/ImageBytesGenerator.kt
  src/test/kotlin/kr/weit/roadyfoody/term/controller/TermControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/service/TermCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/service/TermQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/tourism/presentation/api/TourismControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/domain/UserTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/repository/UserRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/useragreedterm/service/UserAgreedTermCommandServiceTest.kt
Labels: documentation, enhancement

#21 ROFO-58 BE 코드 정리
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/test/presentation/api/TestController.kt
  src/main/kotlin/kr/weit/roadyfoody/test/presentation/spec/TestControllerSpec.kt
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/testcontainers/TestContainersConfig.kt
Labels: documentation, enhancement

#22 ROFO-42 피드백 반영
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/client/KakaoLoginClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/service/ImageServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/utils/MimeUtilsTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/validator/MaxFileSizeValidatorTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/validator/WebPValidatorTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerIntegrateTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/utils/MultipartFileHelper.kt
Labels: enhancement

#20 ROFO-48 음식점 리포트 생성 API
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/config/ConnectionFinder.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/FoodSpotsNameRegex.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/validator/Latitude.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/validator/Longitude.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/validator/WebPImageListType.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/CoordinateUtils.kt
  src/main/resources/application-database.yml
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/utils/MockMvcHelper.kt
Labels: enhancement

#23 ROFO-51 약관 API 피드백 반영 및 패키지 이동
  src/main/kotlin/kr/weit/roadyfoody/auth/application/dto/DuplicatedNicknameResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/dto/KakaoUserResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/dto/SignUpRequest.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/client/KakaoLoginClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/term/application/dto/DetailedTermResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/term/application/dto/SummaryTermsResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/term/application/service/TermCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/term/application/service/TermQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/term/presentation/api/TermController.kt
  src/main/kotlin/kr/weit/roadyfoody/term/presentation/spec/TermControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/application/service/UserAgreedTermCommandService.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/application/service/TermCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/application/service/TermQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/term/fixture/TermDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/term/presentation/api/TermControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/useragreedterm/application/service/UserAgreedTermCommandServiceTest.kt
Labels: documentation, enhancement
