Repository Weit-2nd/roady-foody-server, pull requests merged in 2024-10, with the labels that each got.

#96 ROFO-190 리뷰 신고 API 작성 및 회원탈퇴 시 리뷰 신고 Entity 제거
  src/main/kotlin/kr/weit/roadyfoody/badge/domain/Badge.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewFlagCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/ReviewFlagAlreadyExistsException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewFlagController.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/spec/ReviewFlagControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewFlagRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewFlagCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewFlagControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewFlagRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: documentation, enhancement, refactor

#97 ROFO-235 검색어 순위 구현
  .github/workflows/testRunner.yml
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/global/cache/CacheLoader.kt
  src/main/kotlin/kr/weit/roadyfoody/global/cachekey/PublicCacheKey.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/EnablePropertiesConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/OpenSearchConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/OpenSearchProperties.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/RedisConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/application/service/AddressSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/domain/FoodSpotsSearchHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsPopularSearchesResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/repository/FoodSpotsSearchHistoryRepository.kt
  src/main/resources/application-open-search.yml
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/cache/CacheLoaderTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/application/service/AddressSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/fixture/SearchFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/repository/FoodSpotsSearchHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/testcontainers/TestContainersConfig.kt
Labels: enhancement

#98 [feature/ROFO-239] 랭킹 리스트 - 프로필 이미지 url, 랭킹 변동값 수정
  src/main/kotlin/kr/weit/roadyfoody/global/service/StorageService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
Labels: refactor
