Repository Weit-2nd/roady-foody-server, pull requests merged in 2024-07, with the labels that each got.

#26 ROFO-64 Swagger 에러 ApiResponse 커스텀 어노테이션으로 대체
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/RoadyFoodyBadRequestException.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ApiErrorCodeExample.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ApiErrorCodeExamples.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ExampleHolder.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/spec/AddressSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/tourism/presentation/spec/TourismControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchControllerTest.kt
Labels: documentation, refactor

#24 ROFO-62 음식점 리포트 목록 조회
  src/main/kotlin/kr/weit/roadyfoody/common/dto/SliceResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/SliceReportHistories.kt
  src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/KotlinJDSLUtil.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/RepositoryTest.kt
Labels: enhancement

#25 ROFO-59 로그인 및 인증 필터 구현
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/auth/application/dto/ServiceTokensResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/MissingSocialAccessTokenException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserNotRegisteredException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/CustomUserDetailService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/LoginUser.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/LoginUserResolver.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/filter/JwtFilter.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/filter/MockPassFilter.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/jwt/HMacKeyGenerator.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/jwt/JwtProperties.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/jwt/JwtUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/EnablePropertiesConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/WebMvcConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/user/repository/UserRepository.kt
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/security/LoginUserResolverTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/security/filter/JwtFilterTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/security/jwt/JwtUtilTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/TestSecurityConfig.kt
Labels: documentation, enhancement

#27 ROFO-67 가게 조회를 위한 인덱스 설계
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/RoadyFoodyBadRequestException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ApiErrorCodeExample.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ApiErrorCodeExamples.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/ExampleHolder.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/spec/AddressSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/tourism/presentation/spec/TourismControllerSpec.kt
  src/main/resources/db/migration/V5__create_index_food_spots.sql
  src/test/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/tourism/presentation/api/TourismControllerTest.kt
Labels: documentation

#28 ROFO-75 User nickname 유효 범위 증가 (한글 자/모음 추가)
  src/main/kotlin/kr/weit/roadyfoody/user/utils/NickNameRegex.kt
  src/test/kotlin/kr/weit/roadyfoody/user/domain/UserTest.kt
Labels: enhancement

#29 ROFO-86 회원가입, 토큰 갱신 API 피드백 반영
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
Labels: documentation, enhancement

#30 ROFO-79 리포트 내역 추가 테이블 설계
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportOperationHoursId.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/FoodSpotsNameRegex.kt
  src/main/resources/db/migration/V6__create_report_food_categories_and_operation_hours.sql
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
Labels: documentation

#33 ROFO-65 가게 리포트 가게 유형 추가
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHoursId.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsPhoto.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportOperationHoursId.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/CategoriesNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSportsOperationHoursRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportFoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportOperationHoursRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/OperationHoursRegex.kt
  src/main/resources/db/migration/V7__Increase_photos_file_name_size.sql
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodCategoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportFoodCategoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsServiceTest.kt
Labels: documentation, enhancement

#32 ROFO-74 회원탈퇴 API 작성
  src/main/kotlin/kr/weit/roadyfoody/auth/application/event/AuthEventHandler.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/event/AuthLeaveEvent.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/AuthExceptions.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/InvalidTokenException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/MissingSocialAccessTokenException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserAlreadyExistsException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserNotRegisteredException.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/LoginUserResolver.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/config/ApiDocsConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/term/presentation/spec/TermControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/useragreedterm/repository/UserAgreedTermRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/service/ImageServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/useragreedterm/repository/UserAgreedTermRepositoryTest.kt
Labels: documentation, enhancement

#31 ROFO-63 사용자 거리 이내 가게 조회
  src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
  src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/DayOfWeek.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/KotlinJDSLUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/spec/AddressSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/tourism/presentation/spec/TourismControllerSpec.kt
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/service/FoodSpotsServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/tourism/presentation/api/TourismControllerTest.kt
Labels: enhancement

#35 ROFO-96 CQRS 패턴 적용
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/SliceReportHistories.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
Labels: enhancement

#34 ROFO-95 리뷰 생성
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsPhoto.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ReviewDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReviewPhoto.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/FoodSpotsNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewController.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/spec/ReviewControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSportsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewControllerTest.kt
Labels: enhancement

#36 ROFO-77 코인 소모 시스템
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/RedisLockFailedException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportFoodCategory.kt
  src/main/kotlin/kr/weit/roadyfoody/global/redisson/RedisLockUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/mission/domain/RewardPoint.kt
  src/main/kotlin/kr/weit/roadyfoody/mission/domain/Rewards.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/application/service/AddressSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/dto/AddressResponseWrapper.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/dto/AddressSearchResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/client/KakaoAddressClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/spec/AddressSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/User.kt
  src/main/resources/db/migration/V8__create_rewards.sql
  src/main/resources/db/migration/V9__alter_add_coin_column_on_users.sql
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/fixture/AddressFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/tourism/presentation/api/TourismControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: enhancement

#37 ROFO-105 백도어 관련 API 작성 (개발환경 토큰생성 편의)
  src/main/kotlin/kr/weit/roadyfoody/admin/application/service/AdminCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/application/service/AdminQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/dto/AdminDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/presentation/api/AdminController.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/presentation/spec/AdminControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/auth/security/config/SecurityConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/application/service/AdminCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/application/service/AdminQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/fixture/AdminDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/presentation/api/AdminControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: documentation, enhancement

#38 ROFO-107 카테고리 조회 API
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/FoodCategoriesDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodCategoriesQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodCategoriesController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodCategoriesControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodCategoriesQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodCategoriesControllerTest.kt
Labels: enhancement

#39 ROFO-104 분산락 AOP 적용
  src/main/kotlin/kr/weit/roadyfoody/auth/presentation/client/KakaoLoginClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/annotation/AopForTransaction.kt
  src/main/kotlin/kr/weit/roadyfoody/global/annotation/ClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/global/annotation/DistributedLock.kt
  src/main/kotlin/kr/weit/roadyfoody/global/annotation/DistributedLockAop.kt
  src/main/kotlin/kr/weit/roadyfoody/global/redisson/RedisLockUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/client/KakaoAddressClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/tourism/presentation/client/TourismClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/UserCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/User.kt
  src/test/kotlin/kr/weit/roadyfoody/RoadyFoodyApplicationTests.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/aop/DistributedAopTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/RepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/annotation/ServiceIntegrateTest.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/testcontainers/TestContainersConfig.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/UserCommandServiceTest.kt
Labels: enhancement, refactor

#40 ROFO-106 FoodSpots 생성 리포트 작성 시 코인 적립 로직 추가
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/mission/domain/RewardPoint.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
Labels: enhancement

#41 ROFO-97 리포트 회원 탈퇴시 처리
  src/main/kotlin/kr/weit/roadyfoody/auth/application/event/AuthEventHandler.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportFoodCategoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportOperationHoursRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSportsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportFoodCategoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportOperationHoursRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#43 ROFO-100 가게 운영시간 오픈 스케쥴링
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceIntegrationTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/aop/DistributedAopTest.kt
Labels: enhancement

#42 ROFO-103 24시간 이내 코인이 소모된 거리 이내의 검색은 코인 소모를 안함
  src/main/kotlin/kr/weit/roadyfoody/global/config/RedisConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/domain/SearchCoinCache.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/repository/SearchCoinCacheRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/repository/SearchCoinCacheRepositoryTest.kt
Labels: enhancement

#44 ROFO-119 음식점 정보 수정 리포트 API 작성
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsOperationHours.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/UserCommandServiceTest.kt
Labels: documentation, enhancement, refactor

#45 ROFO-109 로그인 유저 정보 조회 API 작성
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: documentation, enhancement

#46 ROFO-123 리포트와 리뷰 삭제 API
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/FoodSpotsHistoryNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/NotFoodSpotsHistoriesOwnerException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/FoodSpotsReviewNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/NotFoodSpotsReviewOwnerException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewController.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/spec/ReviewControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: enhancement

#47 ROFO-124 잘못된 유저 히스토리 검색 API path 수정
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/FoodCategoryResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ReviewRequest.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReportHistoriesResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/utils/SliceReportHistories.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: bug, enhancement

#48 ROFO-121 좌표를 받으면 주소로 변환해주는 API
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/validator/Latitude.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/validator/Longitude.kt
  src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/application/service/AddressSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/dto/Point2AddressResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/dto/Point2AddressWrapper.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/client/KakaoPointClientInterface.kt
  src/main/kotlin/kr/weit/roadyfoody/search/address/presentation/spec/AddressSearchControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/application/service/AddressSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/fixture/AddressFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/search/address/presentation/api/AddressSearchControllerTest.kt
  src/test/resources/payload/point-to-address-response.json
Labels: enhancement
