Repository Weit-2nd/roady-foody-server, pull requests merged in 2024-08, with the labels that each got.

#49 ROFO-120 리뷰(가게/유저)/리포트 상세 조회 API
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/FoodSpotsHistoryNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportOperationHoursRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/utils/SliceFoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ReviewDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/FoodSpotsReviewNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/exception/ReviewNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReviewResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/utils/SliceUserReview.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/ReportOperationHoursRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/Constants.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: enhancement

#53 ROFO-143 음식점 상세 조회
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
Labels: enhancement

#54 ROFO-134 리포트 생성 일일 제한 로직 추가
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/event/ReportErrorCompensatingTxSync.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/TooManyReportRequestException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceIntegrationTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
Labels: documentation, enhancement

#52 ROFO-135 FoodSpotsHistories 테이블에 reportType 컬럼 추가
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportReward.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/ReportType.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/AlreadyClosedFoodSpotsException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/main/resources/db/migration/V10__alter_add_report_type_column_on_food_spots_histories.sql
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
Labels: documentation, enhancement

#57 ROFO-139 유저 정보 변경 API
  src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoRequest.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/User.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/support/utils/MockMvcHelper.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: enhancement

#56 ROFO-150 로그인 유저 정보 조회 API 에 잔여 당일 리포트 생성 횟수 추가
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceIntegrationTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
Labels: documentation, enhancement

#55 ROFO-149 음식점 수정 리포트 API 수정 대상에 사진 추가
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpotsHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/exception/UnauthorizedPhotoRemoveException.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSportsControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
Labels: documentation, enhancement

#58 ROFO-156 리뷰 갯수/ 평균 별점 조회
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: enhancement

#63 ROFO-140 이미지 다운로드 개선
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
Labels: refactor

#61 ROFO-157 유저 일일 리포트 생성 횟수 변경 API 작성
  src/main/kotlin/kr/weit/roadyfoody/admin/application/service/AdminCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/application/service/AdminQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/presentation/api/AdminController.kt
  src/main/kotlin/kr/weit/roadyfoody/admin/presentation/spec/AdminControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/application/service/AdminCommandServiceIntegrationTest.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/application/service/AdminCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/admin/presentation/api/AdminControllerTest.kt
Labels: documentation, enhancement

#62 [ROFO-160] 코인 소모량 조회 API
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/RequiredCoinRequest.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoResponse.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/fixture/SearchFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
Labels: documentation

#64 ROFO-175 FoodSports -> FoodSpots 오탈자 수정
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSpotsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsOperationHoursRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceIntegrationTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
Labels: refactor

#66 ROFO-186 좋아요 테이블 설계
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ReviewDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/ReviewLike.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/ReviewLikeId.kt
  src/main/resources/db/migration/V14__create_review_like_and_alter_add_like_column_on_reviews.sql
  src/main/resources/db/migration/V16__alter_column_rename_reviews_like.sql
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
Labels: enhancement

#67 ROFO-176 승급보상획득내역 테이블 추가 및 관련 변경 사항 적용
  src/main/kotlin/kr/weit/roadyfoody/badge/domain/Badge.kt
  src/main/kotlin/kr/weit/roadyfoody/badge/domain/UserPromotionRewardHistory.kt
  src/main/kotlin/kr/weit/roadyfoody/user/domain/User.kt
  src/main/resources/db/migration/V15__create_user_promotion_reward_histories.sql
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: enhancement

#69 ROFO 181 리포트 랭킹 구현, 조회 api 개발
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/SchedulingConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/resources/db/migration/V17__alter_composite_index_food_spots_histories.sql
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingControllerTest.kt
Labels: enhancement
