Repository Weit-2nd/roady-foody-server, pull requests merged in 2024-09, with the labels that each got.

#70 [ROFO-182] 리뷰 랭킹 구현, 조회 api
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/AsyncConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/SchedulingConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/dto/UserRanking.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/utils/RankingConstans.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/rewards/presentation/spec/RewardsControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/fixture/RankingFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#71 ROFO-193 뱃지 기준 음식점 리뷰 조회 로직 추가
  src/main/kotlin/kr/weit/roadyfoody/badge/domain/Badge.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsController.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSpotsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReviewResponse.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/presentation/api/FoodSpotsControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#72 ROFO-194 사용자 정보 조회 API 반환결과에 뱃지 추가
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
Labels: enhancement

#73 ROFO-185 좋아요 증가&감소
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/presentation/spec/FoodSpotsControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/global/cachekey/PublicCacheKey.kt
  src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ToggleLikeResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewLikeController.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/spec/ReviewLikeControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewLikeControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
Labels: enhancement

#74 ROFO-211 OpenSearch 연동
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/RoadyFoodyApplication.kt
  src/test/kotlin/kr/weit/roadyfoody/support/config/testcontainers/TestContainersConfig.kt
Labels: enhancement

#76 [ROFO-183] 좋아요 랭킹
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/exception/RankingNotFoundException.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/utils/RankingConstans.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#75 ROFO-205 searchFoodSpots 응답 데이터 추가
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/global/utils/KotlinJDSLUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/fixture/FoodSpotsFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsPhotoRepositoryTest.kt
Labels: enhancement

#77 ROFO-188 유저 탈퇴시 좋아요 감소 처리
  src/main/kotlin/kr/weit/roadyfoody/auth/application/event/AuthEventHandler.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
Labels: enhancement

#79 [Feature/ROFO-184] 종합랭킹
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/utils/RankingConstans.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#84 [ Feature/ROFO-218] 로컬캐시 적용/ Redis Pub-sub을 이용하여 로컬캐시 동기화
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/global/cache/CacheLoader.kt
  src/main/kotlin/kr/weit/roadyfoody/global/cache/CachePublisher.kt
  src/main/kotlin/kr/weit/roadyfoody/global/cache/CacheSubscriber.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/CacheConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/global/config/RedisConfig.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/utils/RankingConstans.kt
  src/test/kotlin/kr/weit/roadyfoody/global/cache/CacheLoaderTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
Labels: enhancement

#81 ROFO-217 circuitbreaker 적용 (resilience4j)
  build.gradle.kts
  src/main/kotlin/kr/weit/roadyfoody/auth/security/jwt/JwtUtil.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/service/FoodSpotsCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/global/annotation/DistributedLockAop.kt
  src/main/kotlin/kr/weit/roadyfoody/global/circuitbreaker/alert/CircuitBreakerStatusAlert.kt
  src/main/kotlin/kr/weit/roadyfoody/global/circuitbreaker/targetexception/RedisCircuitBreakerTargeException.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/service/FoodSpotsSearchService.kt
  src/main/resources/application-resilience4j.yml
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/roadyfoody/global/circuitbreaker/RedisCircuitBreakerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/global/circuitbreaker/alert/CircuitBreakerStatusAlertTest.kt
Labels: enhancement

#82 ROFO-187 유저가 좋아요 누른 리뷰 조회 및 리뷰 조회시 좋아요 수 프로퍼티 추가
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/application/dto/ReportDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReviewResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/utils/SliceUserLike.kt
  src/main/resources/db/migration/V18__alter_created_date_time_index.sql
  src/test/kotlin/kr/weit/roadyfoody/global/Constants.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: enhancement

#85 [feature/ROFO-221] 음식점 정보 리스트 응답값 - 푸드트럭 여부 추가
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReportHistoriesResponse.kt
Labels: enhancement

#86 [feature/ROFO-220] 유저조회 응답값에 순위 추가
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/dto/UserRanking.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserInfoResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/fixture/RankingFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserDtoFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
Labels: enhancement

#89 ROFO-230 좋아요 ID 만들기
  src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/ReviewLike.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/ReviewLikeId.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReviewResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/main/resources/db/migration/V19__alter_add_id_on_review_like.sql
  src/main/resources/db/migration/V20__alter_drop_index_and_create_unique_on_review_likes.sql
  src/test/kotlin/kr/weit/roadyfoody/global/Constants.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewLikeCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: bug

#88 ROFO-222 유저 활동 통계 API
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/dto/UserReviewResponse.kt
  src/main/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/api/UserController.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/application/service/UserQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/user/presentation/api/UserControllerTest.kt
Labels: enhancement

#91 ROFO-233 리뷰 삭제시 좋아요도 삭제
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/ReviewLikeRepositoryTest.kt
Labels: documentation

#90 ROFO-204 리뷰 수정
  src/main/kotlin/kr/weit/roadyfoody/review/application/dto/ReviewDtos.kt
  src/main/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/review/domain/FoodSpotsReview.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewController.kt
  src/main/kotlin/kr/weit/roadyfoody/review/presentation/spec/ReviewControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/user/presentation/spec/UserControllerSpec.kt
  src/main/resources/db/migration/V21__alter_add_updated_datetime_column_on_reviews.sql
  src/test/kotlin/kr/weit/roadyfoody/review/application/service/ReviewCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/fixture/ReviewFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/presentation/api/ReviewControllerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewPhotoRepositoryTest.kt
Labels: enhancement

#92 [Feature/ROFO-232] 랭킹 리스트 응답값 수정
  src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepository.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/dto/UserRanking.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/main/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepository.kt
  src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsHistoryRepositoryTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/fixture/RankingFixture.kt
  src/test/kotlin/kr/weit/roadyfoody/review/repository/FoodSpotsReviewRepositoryTest.kt
Labels: enhancement

#94 [feature/ROFO-234] 랭킹 리스트 조회 요청값에 start 추가
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingCommandService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryService.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingController.kt
  src/main/kotlin/kr/weit/roadyfoody/ranking/presentation/spec/RankingControllerSpec.kt
  src/test/kotlin/kr/weit/roadyfoody/global/Constants.kt
  src/test/kotlin/kr/weit/roadyfoody/global/circuitbreaker/RedisCircuitBreakerTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/application/service/RankingQueryServiceTest.kt
  src/test/kotlin/kr/weit/roadyfoody/ranking/presentation/api/RankingControllerTest.kt
Labels: enhancement
